
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Site settings
title: "Echoes of the Keep"
description: Internal documentation for the team.

# Navigation settings
aux_links:
  "View on GitHub": https://github.com/0ksa1/OHTU2HIJNPW